#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	active_color=0xffe2e2e3 #0xffe1e3e4 #0xffc29df1 
    inactive_color=0xc02c2e34 #0xff494d64 #0xff182c2c #0xff414550  #0xffc29df1
	background_color=0x302c2e34
)

borders "${options[@]}"
