require("items.apple")
require("items.rift")
-- require("items.aero_icons")
-- require("items.hyprspace_icons")
--require("items.spaces")
require("items.menus")
require("items.front_app")
require("items.calendar")
require("items.widgets")
require("items.media")
